// 364 Ways to Say No - Complete Collection
// Generated automatically

export const QUOTES_364 = {
  free: [
  "\u201cI used extra-strength fabric softener and now my sheets are so slippery I\u2019ll slide off the bed like a wet seal.\u201d",
  "I can\u2019t tonight. My cat\u2019s therapist says she needs more one\u2011to\u2011one time.",
  "\u201cI would, but I\u2019ve already taken my bra off and that\u2019s the final stage of the evening.\u201d"
],
  unlocked: [
  "I can't \u2014 Maureen did that and lost custody of something important.",
  "Excel just gaslit me for 45 minutes. I need recovery time.",
  "Not tonight \u2014 I've got wind issues and I'm not risking an enclosed space with people.",
  "Not tonight \u2014 I\u2019ve finally got the heating exactly right and I don\u2019t want to disturb the balance.",
  "I can't tonight \u2014 I can't go back to that library.",
  "Not tonight \u2014 my MIL texted something that suggests she's got opinions about tonight.",
  "Terribly sorry \u2014 my diary says \u201cavoid people\u201d in very large font.",
  "Not tonight \u2014 I'm banned from the Tesco on the high street and I'm not explaining why.",
  "Not tonight \u2014 my MIL's invited herself over and I need time to prepare emotionally.",
  "Sunshine, you\u2019re missing the plot by about three episodes.",
  "Can\u2019t \u2014 I\u2019ve spotted a pigeon on the fence and I need to monitor the situation.",
  "I can't tonight \u2014 I'm on chapter 47 of a book and the protagonist just made a terrible decision and I need to see if they survive it.",
  "Not tonight \u2014 I\u2019m in the middle of a very tense game of \u2018Where\u2019s that smell coming from?\u2019",
  "Not tonight \u2014 Margaret tried this once and she's been in therapy since.",
  "Not tonight \u2014 the cat's staring at nothing and I need to know if she's dying or just being dramatic.",
  "Not a chance, darling. My perm's still setting and you know what they say about damp rollers and romance.",
  "Not tonight \u2014 someone will ask me questions and my vague answers aren't vague enough yet.",
  "\u201cSorry love, my schedule\u2019s tight tonight\u2026 and so is my blanket.\u201d",
  "I would, but I\u2019ve promised myself an early night with a firm pillow and no surprises.",
  "I can't \u2014 something's happened with my underwear situation and I'm managing it alone.",
  "I can't \u2014 I've observed that someone always washes their car on Sundays but last Sunday they didn't and I've become concerned.",
  "Put it away Arthur; I\u2019ve already had my quota of excitement for this decade.",
  "I\u2019ve offended a seagull and now I\u2019m in hiding.",
  "Can't tonight\u2014I've got to text my mate about what she said at bingo and it absolutely cannot wait.",
  "I got out of the car like a crime scene documentary extra.",
  "Sorry, but my phone storage is judging me.",
  "Not tonight \u2014 I\u2019m waiting for my laundry to finish so I can ignore it.",
  "Not tonight \u2014 the dog needs to go out and come back in approximately 47 times and I'm the only one who understands her terms.",
  "The silence is finally returning my calls.",
  "Not tonight \u2014 I\u2019ve got to re\u2011label all my spice jars after the cumin incident.",
  "I would, but I\u2019ve promised the dog I\u2019d help him stare at nothing in particular.",
  "Not tonight \u2014 I\u2019m counting how many times the boiler clicks before bed.",
  "I can\u2019t. My neighbour\u2019s parrot escaped again and I\u2019m legally involved now.",
  "I can't \u2014 I wore jeans with a real waistband and now I must lie down for 6 hours.",
  "My cat just gave me a look that said \u201cyou\u2019re not going anywhere\u201d.",
  "The app crashed and took my entire personality with it.",
  "Can't tonight\u2014I've got a rogue eyebrow that's demanding my full attention.",
  "Not tonight \u2014 Linda from reception said the last person who did this isn't permitted to come in on Thursdays.",
  "I can't \u2014 I've decided I'm too old to pretend to care about this and I need to sit with that freedom.",
  "Not tonight \u2014 I've got a 'do not disturb' status and I'm taking that very seriously.",
  "Not tonight \u2014 something's shifted in my pelvis and I need to sit very still.",
  "Not tonight \u2014 the rabbit has done something and I need to determine if it's a warning or a demand.",
  "Kevin, my love, you\u2019re really out here recycling the same script. Cute.",
  "I can't tonight \u2014 Edna from bingo said she knew someone who did that and the council got involved.",
  "I can't \u2014 I've said something in a group chat and now I must monitor the response with paranoia.",
  "Sorry, flower. The milkman left rather a lot this morning and I\u2019m still trying to get the cream off the top.",
  "My third eye is closed for maintenance.",
  "I sat in the wrong chair and now I\u2019m committed to this ache.",
  "Not tonight \u2014 Rachel from admin said someone tried this and it became a policy update.",
  "Sorry, but something feels legally suspicious.",
  "Not tonight \u2014 my MIL's made a passive-aggressive comment and I'm still processing it.",
  "Can't do it. My sister's neighbour's psychic says there's a tall dark stranger coming, but apparently it's the gas man.",
  "I can't \u2014 I'm exhausted from the mental gymnastics required to make underwhelming work.",
  "Not tonight \u2014 I was fine until someone mentioned 'staying up late' and now I'm exhausted on principle.",
  "I can't \u2014 something I ate is having second thoughts and so am I.",
  "I\u2019ve opened the posh crisps. Protocol has been activated.",
  "Sorry \u2014 I\u2019ve just turned the big light off and there\u2019s no going back.",
  "Not tonight \u2014 I've just found out my Spotify Wrapped was right about me and I'm processing.",
  "Sweetheart, point very much missed. Again.",
  "I can\u2019t, love. I\u2019ve gone into \"Power Save\" mode and my battery is currently at 2%.",
  "Can't tonight\u2014I'm mentally preparing to ring the council about a pothole. They said to call back between 2 and 2:15pm next Thursday.",
  "Can't, I'm afraid. I've promised the budgie I'll read him the new Argos catalogue cover to cover.",
  "Not tonight, love. I've got a suspicious twinge in my shoulder and I need to Google it until 2am.",
  "Babe\u2026 you\u2019re doing the thing again. We both know how this movie ends.",
  "Cat sat on the keyboard and typed \u201cno\u201d seventeen times.",
  "I can't \u2014 Wendy did that and she had to move to a different town.",
  "Sorry, love \u2014 I\u2019ve just put a wash on and you know you can\u2019t start anything new once the spin cycle begins.",
  "Not tonight, darling. I've got to finish this crossword clue or it'll haunt me for the next fortnight.",
  "I can't \u2014 I'm watching someone's Instagram story on mute to gather intelligence and I can't break my cover.",
  "I can't \u2014 I knew someone whose pet did something irreversible and now certain animals make me nervous.",
  "I\u2019ll have to give that a miss, if it\u2019s all the same to you.",
  "I can't \u2014 I'm genuinely tired of the gap between what was implied and what showed up.",
  "My soup is at the perfect temperature. I cannot abandon it.",
  "I can't \u2014 I've got 6 unread notifications and I'm not emotionally prepared for even one of them.",
  "Sorry, but I\u2019m emotionally buffering.",
  "I would, but I\u2019ve promised myself I\u2019d finally Google that rash.",
  "Not tonight, darling. The curtains need ironing and they're mocking me from the window.",
  "I can\u2019t, darling. I\u2019ve just sat down and you know how long that took.",
  "Kevin\u2026 point missed, map lost, GPS turned off. Iconic.",
  "I can't tonight \u2014 I've noticed a neighbour has two identical cats and I'm trying to figure out if one is a decoy.",
  "Not tonight \u2014 I\u2019ve got to re\u2011fold the towels because someone did it \u2018wrong\u2019 again.",
  "I can't \u2014 Karen did something similar and lost her job because of it.",
  "Kevin. My guy. You\u2019re really out here thinking I don\u2019t remember chapter one?",
  "Not tonight Dave \u2014 I\u2019ve pulled something reaching for the remote.",
  "Not tonight \u2014 I\u2019m waiting to see if this paracetamol works or if I\u2019m dramatic.",
  "Not tonight \u2014 someone's posted something vague and cryptic and now I'm trying to decode what happened.",
  "Not tonight \u2014 I'm in 3 group chats that are happening simultaneously and I'm choosing none of them.",
  "Not tonight \u2014 my underwear situation requires immediate home intervention.",
  "Not tonight\u2014I'm in the middle of a very important disagreement with myself about whether I've locked the back door.\"",
  "Not tonight \u2014 there's a person in our circle who did this and nobody brings it up anymore.",
  "I can\u2019t \u2014 Outlook has defeated me.",
  "My introvert alarm just went off. Loudly.",
  "Kevin. We\u2019ve literally done this scene. I know your lines.",
  "I can't \u2014 someone I know once had to explain an injury involving furniture and I've never trusted that furniture since.",
  "Not tonight Brian \u2014 that won\u2019t be necessary.",
  "Not tonight \u2014 Susan attempted this and her marriage never recovered.",
  "I can't \u2014 something's gone numb in a way that's concerning and I need medical attention (or rest, I'm not sure).",
  "I would, but I\u2019ve got to supervise the washing machine. It gets ideas above its station.",
  "I can't tonight \u2014 a friend once had a thing and now whenever I see a similar thing, I remember it.",
  "I can't \u2014 my grandad mentioned his Tesco incident once and then refused to elaborate.",
  "Not tonight \u2014 I sneezed and something in my shoulder changed. I must investigate.",
  "I\u2019m in a passive-aggressive stand-off with my router.",
  "I can\u2019t \u2014 I\u2019ve upset a pigeon.",
  "I can't \u2014 my mother-in-law's going to ask about something and I'm not prepared to answer.",
  "Not tonight \u2014 I\u2019m trying to remember the name of that actor from that thing.",
  "That's very kind, but I'm going to have to ask you not to ask again.",
  "Not tonight \u2014 I\u2019m waiting for the cat to decide which room he wants to be in.",
  "Sorry, but I\u2019m unavailable for enthusiasm this evening.",
  "Not tonight, darling. I've got to finish this episode of casualty or I'll burst.",
  "I\u2019ve committed an unforgivable amount of cheese tonight.",
  "I would, but I've promised to help Margaret sort her pet budgie`s medication by day of the week and apparently I'm the only one she trusts.",
  "Not tonight\u2014I\u2019ve decided to see how long I can go without blinking while staring at this picture of a spaniel.",
  "Darling, no \u2014 I need a full orchestra, not a man turning up with a recorder.",
  "I can't tonight \u2014 Tracy did something like that once and she's only got one leg now.",
  "Not tonight \u2014 there's a person who did this and now they don't come to group things anymore.",
  "Sorry \u2014 I\u2019ve started scrolling and I don\u2019t know where the bottom is.",
  "I can't \u2014 Kevin mentioned his mate did this and 'let's just say the company's lawyers were involved.",
  "I can't tonight \u2014 I've got a situation with my pants that requires privacy.",
  "The parrot said \u201cstay home\u201d and I respect his opinion.",
  "Not tonight \u2014 I'm at the exact stage of the friendship where I still have to try and I'm exhausted by that.",
  "Darling, you\u2019re giving main-character energy to a very side-character move.",
  "My password manager is judging me.",
  "Not tonight \u2014 a work friend mentioned their sister's situation with a garden gnome and it's haunting me.",
  "Not tonight \u2014 my hands have decided they're not gripping things today.",
  "How frightfully kind. Do pester me again when I'm accepting visitors. (I'm not.)",
  "The oven is preheating. We\u2019re married now.",
  "Not tonight \u2014 someone I went to school with has posted something and the comments are a mess and I'm reading every single one.",
  "Sorry, but I\u2019ve opened the good chocolate.",
  "Not tonight \u2014 my neighbour mentioned her daughter's boyfriend's van and now I'm worried about what's in it.",
  "I\u2019ve already performed emotional labour for capitalism today.",
  "I can't \u2014 I've decided someone owes me an apology and I'm rehearsing how to mention it.",
  "I\u2019m busy trying to teach my Alexa how to speak with a Geordie accent and it\u2019s a full-time commitment.",
  "I\u2019ve entered the \u201chave you tried turning it off and on again\u201d stage of grief.",
  "I can't \u2014 someone's relative's pet has created a smell situation and I'm implicated just by living here.",
  "I can\u2019t \u2014 the situation lacks stability.",
  "\u201cAw babe, I\u2019m taken \u2014 by the couch. It\u2019s serious.\u201d",
  "I can't tonight. My friend's told me something outrageous about someone at the coffee morning and I need to process it in private.",
  "Not tonight \u2014 I'm in the middle of a mystery novel and I've just figured out who did it but I need to confirm I'm right.",
  "Not tonight \u2014 I've opened the fancy biscuits and I must commit to finishing them tonight or they'll stale.",
  "Not a chance. My best bra\u2019s on strike and the girls refuse to come.",
  "The fridge light judged me when I opened it. I can\u2019t leave now.",
  "\u201cThanks for the invite, but I\u2019m already in bed with a good book.\u201d",
  "Not tonight \u2014 Pam tried this and she had a nervous breakdown that took years to recover from.",
  "I can't \u2014 I've decided I'm not the kind of person who goes out on Thursdays and I need to commit to that brand.",
  "Not tonight, darling. The telly's on and there's a rerun of Murder, She Wrote and Angela Lansbury's looking directly at me.",
  "I can't \u2014 my partner's in a mood and I'm not risking making it worse by leaving.",
  "Not tonight \u2014 Janet at bingo mentioned this exact thing happening to her cousin and it took six months to resolve.",
  "The houseplants are giving me attitude. I need to negotiate.",
  "Not tonight, dear. I\u2019ve just started a very intense relationship with a new brand of digestive biscuit.",
  "Sorry, pet. I've promised the cat I'll watch the Bridgerton with him. He gets very emotional when the queens on.",
  "My back just filed for divorce.",
  "Not tonight \u2014 something's itching internally in a way I can't explain and I'm staying home.",
  "I appreciate your optimism about my availability.",
  "I can't \u2014 he mentioned something earlier and I'm still processing what he meant by it.",
  "Not tonight \u2014 my nan tried that and she's still not allowed back at the Post Office.",
  "Not tonight \u2014 my mate's having a crisis about something and I'm the only one she'll talk to.",
  "Not tonight \u2014 my gran did something similar and now she uses her mate's loyalty card so nobody knows it's her.",
  "Oh sweetheart, I would, but my lucky knickers are in quarantine.",
  "I can't \u2014 a mate told me something about a public toilet and now I've got that information forever.",
  "Not tonight \u2014 Debbie tried it and she got arthritis and nobody knows if they're connected but they might be.",
  "Not a chance. The Avon lady's coming tomorrow and I need to look rested and slightly mysterious.",
  "I can\u2019t \u2014 I\u2019m keeping an eye on a cloud that looks like David Hasselhoff.",
  "I can't \u2014 there's hair growing where it shouldn't and I haven't time to address it.",
  "Not tonight \u2014 I stood up from sitting and made three separate noises. It's a bad sign.",
  "Not tonight \u2014 I've noticed the neighbours doing something odd and I've got research hours ahead.",
  "Not tonight \u2014 I slept on my arm weird and it's made a noise that concerns me.",
  "Not tonight \u2014 I've watched someone try to unmute for 8 minutes and it's drained my patience reserves.",
  "Not tonight \u2014 a friend of mine got stuck in something embarrassing and now I'm paranoid about all similar situations.",
  "I\u2019ve upset the energy of the room and now I must atone.",
  "Not tonight \u2014 I\u2019ve promised the neighbours I\u2019d stop making noises after 7pm.",
  "I can\u2019t \u2014 I updated something and now nothing works.",
  "I made a noise getting out of bed that legally counts as a cry for help.",
  "Not tonight \u2014 I've noticed something about the paint and now I've got opinions.",
  "I can't \u2014 I wore new shoes for 20 minutes and now my feet are staging a formal protest.",
  "I can't \u2014 my autocorrect just suggested something that made me question my entire phone.",
  "Not tonight, darling. I'm in the middle of a very heated debate with myself about whether I unplugged the hair straighteners.",
  "I would, but I\u2019m trying to hear what the people on the next table are arguing about.",
  "\u201cI\u2019d love to, but I\u2019m already fully stretched out in commitment.\u201d",
  "Sorry petal \u2014 I\u2019ve got to finish knitting a scarf for a goose I met in Skegness.",
  "Can't, darling. My support tights have developed a ladder and it's heading straight for my dignity.",
  "You\u2019re lovely, but I\u2019m afraid my boiler\u2019s acting up and I\u2019m waiting for a man with a much larger wrench.",
  "Not tonight \u2014 Maureen said her late husband tried something similar and the insurance company had words.",
  "I can\u2019t, love. I\u2019ve just greased my muffin tins and if I start sliding around now, there\u2019ll be an incident.",
  "I can\u2019t tonight. I\u2019m waiting for a parcel and the driver\u2019s \u2018two stops away\u2019 for the next six hours.",
  "I'd rather not. The neighbours have just got a water bed and the walls are thinner than my patience.",
  "I can't \u2014 my underwear's decided today's the day it stops working as intended.",
  "I can't tonight \u2014 my grandad did something like that once and he's banned from three places now.",
  "Not tonight, pet. I\u2019ve got to rehearse my disappointed sigh for tomorrow\u2019s meeting.",
  "I would, but I\u2019m saving my energy for something truly disappointing tomorrow.",
  "Not tonight \u2014 my nan did that and now she orders everything online because she can't show her face.",
  "Not now, dear \u2014 I\u2019d prefer not to, thank you.",
  "I\u2019ve committed to staring at the wall with purpose.",
  "I can't \u2014 my grandad warned me very specifically about attempting this.",
  "Sorry, but I bent down and reconsidered my life.",
  "Not tonight \u2014 I'm too aware of what's actually happening to fake enthusiasm about what isn't.",
  "Not tonight Brian \u2014 I\u2019ve opened snacks and that\u2019s binding.",
  "Not tonight \u2014 I\u2019ve committed to doing absolutely nothing and I must see it through.",
  "I can't \u2014 my mother-in-law's been lovely lately and that's more suspicious than when she's difficult.",
  "Not tonight Sid \u2014 I slept slightly wrong and now I live like this.",
  "Not tonight \u2014 I've been asked not to return to that swimming pool.",
  "My knees just sent me a formal complaint.",
  "Not tonight \u2014 I\u2019m emotionally drained from arguing with the self\u2011checkout.",
  "Not now, dear \u2014 I\u2019ve reached the blanket stage of the day.",
  "Aw, you\u2019re doing the hopeful-puppy-eyes sequel. I\u2019ve seen the reviews.",
  "Babe, you\u2019re missing the memo by several time zones.",
  "I can't \u2014 someone's relative brought a parrot to a garden party and it said something weird and now I'm unsettled.",
  "Not tonight \u2014 I've spotted someone's photo from 2009 and now I'm examining their entire Instagram history.",
  "Tempting, but I\u2019ve slipped into something comfortable and I\u2019m not coming back.",
  "I\u2019d rather not put myself through that, thank you ever so much.",
  "I can't \u2014 a 9am meeting overran by 12 minutes and now everything's shifted and I can't readjust.",
  "Not tonight \u2014 Sharon from HR mentioned this came up once and she wasn't allowed to discuss the outcome.",
  "Not tonight \u2014 Brenda attempted this and her family's still not speaking to her.",
  "Sorry, duck. The sheets are freshly ironed and they\u2019re far too crisp to crumple yet.",
  "Not tonight \u2014 I\u2019ve got crumbs in the bed and I need to investigate thoroughly.",
  "Not tonight \u2014 I've tried to log in three times and now I'm locked out and I'm taking it as a sign.",
  "I can't \u2014 my best friend's upset about something and I promised to help process it tonight.",
  "I can\u2019t \u2014 I\u2019m trapped under something furry.",
  "I can't tonight \u2014 Dave from accounts tried something like this and now he works from home permanently.",
  "I can't tonight \u2014 I've got a theory about what's happening in that one house and I need to sit with it.",
  "I can't \u2014 I've got a sweat patch situation that's beyond deodorant's capacity.",
  "Not tonight \u2014 I\u2019m in the middle of a very important sulk.",
  "I can't \u2014 Edna mentioned a person who did this and then moved to Swindon very suddenly.",
  "I can't \u2014 I've started a true crime podcast and I'm three episodes in and now I'm convinced someone I know is suspicious.",
  "I can\u2019t. I\u2019m waiting for the washing machine to finish its dramatic finale.",
  "Corporate has taken everything from me except this blanket.",
  "I can't \u2014 I'm in a mood where I need substance, not just suggestions of it.",
  "I can't tonight \u2014 I've got a hot flash situation brewing and I'm staying near a fan.",
  "Not tonight \u2014 I've heard a noise at 3am three times this month and I'm now documenting it.",
  "I\u2019d love to, but I\u2019ve just polished the floor and I\u2019m as slippery as a buttered eel on a lino surface.",
  "Not tonight \u2014 I\u2019ve just washed my hair and it\u2019s entered its \u2018don\u2019t touch me\u2019 phase.",
  "Aw bless. Still haven\u2019t realised I keep the receipts, have you?",
  "Not tonight Sid \u2014 I\u2019m supervising a slow-cooked evening.",
  "\u201cI\u2019m afraid I\u2019ve got my hands full\u2026 with a very large mug of tea.\u201d",
  "I would, but the dog next door barked earlier and I\u2019m still thinking about it.",
  "Not tonight \u2014 I'm knackered from managing expectations that refuse to be met.",
  "I\u2019ve already smiled at someone this week. Quota met.",
  "Not tonight, pet \u2014 I\u2019ve promised Mrs Popadoplis I\u2019d help her glue googly eyes onto her garden gnomes.",
  "Not tonight \u2014 a neighbour has a routine that changed this week and now I'm wondering if they're okay or if something happened.",
  "Not tonight \u2014 I\u2019ve got to rotate the mattress and emotionally prepare for it.",
  "Not tonight Dave \u2014 I\u2019ve been adopted temporarily by a dog.",
  "I\u2019ve been cursed by a very small and vindictive ghost.",
  "Not tonight \u2014 I had a friend who got chased by a goose and the trauma is secondhand but real.",
  "Not tonight \u2014 I've remembered that one time I said something weird and everyone's probably still thinking about it.",
  "Not tonight Brian \u2014 I\u2019m fully booked doing nothing.",
  "Sorry love, but my horoscope said \u2018avoid unnecessary drama\u2019 and here we are.",
  "Not tonight, love \u2014 I\u2019ve got to re\u2011train my satnav after it called me \u2018mate\u2019.",
  "Not tonight \u2014 a neighbour casually mentioned their son's roommate situation and now I'm concerned and can't focus.",
  "Not tonight \u2014 the dog's got me pinned to the sofa and honestly, I've accepted my fate.",
  "Not a hope. My best slippers have gone walkabout and I won't be seen hobbling about like a wounded pigeon.",
  "I can't \u2014 I'm scared I'll accidentally be funny and then I'll have to maintain that persona.",
  "Not tonight \u2014 Edna casually mentioned it was illegal in 1987 and nobody checked if that's changed.",
  "I can't \u2014 I saw a light in a supposedly empty building and now I've developed an obsession.",
  "How lovely of you to think of me. Still no.",
  "I can't \u2014 my hormones are having thoughts and I need to let them finish.",
  "The moon is in a mood and I\u2019m not crossing her.",
  "Not tonight\u2014I\u2019ve got a date with a bottle of Pinot and a very large bag of Monster Munch.",
  "I can't tonight \u2014 my stomach's made a decision and I need to stay near the toilet.",
  "I can't \u2014 I've made a sandwich that's too ambitious to move with.",
  "Not tonight \u2014 my pants have given up and I've had to accept a new arrangement.",
  "Not tonight \u2014 something's shifted in my closet and I need to assess the damage.",
  "I can\u2019t \u2014 the dog is asleep on me and that\u2019s law.",
  "I can't \u2014 my mother-in-law's been quiet and that's worse than when she's loud.",
  "I can't \u2014 there's a caf\u00e9 I can no longer visit and the staff know why.",
  "Can\u2019t, pet. I\u2019ve promised the toaster I\u2019d spend more quality time with it.",
  "I can't \u2014 I've seen something at number 47 that suggests a story I don't want to know.",
  "I can't \u2014 Edna said she'd 'seen this before' in a tone that suggested nothing good came of it.",
  "I can't \u2014 someone tried this and had to change their phone number because of the fallout.",
  "Not tonight \u2014 Linda tried this and she had to move house because of the fallout.",
  "Not tonight \u2014 I've already forgiven one thing today and I'm maxed out.",
  "I stood up too quickly and my skeleton said no.",
  "I can't \u2014 I need a night where nothing fails to meet minimum expectations.",
  "I would, but I've got a standing appointment with a very important pot of yoghurt that expires at midnight.\"",
  "I can't \u2014 Janet said her sister-in-law's friend tried that and the samaritans got wind of it.",
  "I can't \u2014 the people two doors down have a situation brewing and I've accidentally got information I shouldn't have.",
  "I can't \u2014 my mum's friend attempted this and her husband found out and that was the beginning of the end.",
  "I can't \u2014 I've accidentally become invested in a minor neighbourhood dispute and I'm gathering evidence.",
  "Not tonight \u2014 Janet mentioned someone did something similar and 'well, they don't live here anymore.",
  "I can't \u2014 I've noticed a neighbour's curtains are never fully closed and I'm trying to respect their privacy while also being curious.",
  "Not tonight \u2014 I'm at capacity for things that don't live up to their promise.",
  "Honey, I\u2019ve got a whole Netflix category named after your excuses.",
  "Not tonight \u2014 Christine from HR's got a face she makes when certain things come up and I've learned to notice that face.",
  "I can't tonight \u2014 my neighbour's sister's dog has done something to the fence and now I'm part of the fallout.",
  "Not tonight \u2014 someone mentioned their cousin's ex lives on this street and now I'm paranoid about who's who.",
  "Not now, darling. I\u2019ve just rubbed in rather a lot of hand cream and things are getting slippery.",
  "\u201cNot tonight \u2014 I\u2019m already getting very comfortable with someone who never disappoints me\u2026 my hot water bottle.\u201d",
  "I can't \u2014 my dog has claimed the bathroom and will not negotiate.",
  "Dog sighed at me like I\u2019m the one who ruined his day.",
  "I can\u2019t \u2014 I\u2019ve got a sock that\u2019s lost its partner and I need to support it.",
  "Not tonight\u2014I\u2019m defrosting a very large ham and it requires my undivided attention.",
  "Not tonight, I\u2019ve just eaten a very large piece of cheddar and I\u2019m preparing for the vivid dreams.",
  "Not tonight \u2014 there's a light that comes on in a house I can see and it's on a schedule that's either routine or suspicious, and I must determine which.",
  "Sorry, but the hamster situation requires calm.",
  "I can't tonight \u2014 I've already had enough disappointment this week and I'm protecting my reserves.",
  "Not tonight \u2014 my cousin's husband's mate did this once and the silence around it has never been broken.",
  "I can't \u2014 my body's doing that thing where it leaks and I'm not confident I can manage it in public.",
  "Not tonight \u2014 my knickers have migrated somewhere they shouldn't be and I need to fix this privately.",
  "\u201cNice try, but I\u2019m already fully committed\u2026 to my duvet.\u201d",
  "I can't \u2014 I had a friend who had a situation involving a mirror and I'm not going into details but I can't look at mirrors the same way.",
  "I can't \u2014 someone's turned their camera on unexpectedly and I've had an identity crisis.",
  "Can't tonight\u2014I've found a stain on the carpet I didn't know about yesterday and I need to decide if I'm upset or not.",
  "Not tonight \u2014 there's a house that got a new fence and the colour choice is raising questions I didn't know I had.",
  "Not tonight \u2014 elastic has failed in an embarrassing location and I'm not risking movement.",
  "Not tonight \u2014 I've done the mental math and the conversation-to-effort ratio is unfavourable.",
  "Can\u2019t \u2014 I\u2019ve got to finish this documentary about a man who collects spoons.",
  "Not tonight, darling. The neighbourhood WhatsApp group's having a crisis about someone's dustbin and I'm moderating.\"",
  "Not tonight Sid \u2014 the evening has gone sideways.",
  "I can't \u2014 I need to sit with the last time something seemed promising then just... wasn't.",
  "Not tonight \u2014 someone's described a medical emergency involving a frozen object and I need to process that.",
  "Dog is using me as an emotional support mattress.",
  "I can't \u2014 I'm at that age where I've stopped being kind about things that simply aren't it.",
  "Not now, dear \u2014 my back made a new sound today.",
  "Not tonight \u2014 I've had to smile professionally so much my face has filed a complaint.",
  "Not tonight \u2014 Rachel attempted this and spent six months in hospital (for reasons she won't discuss).",
  "Not now, dear \u2014 I\u2019ve made tea and plans are cancelled.",
  "I can't \u2014 Michelle did that and she ended up divorced over it.",
  "I can\u2019t \u2014 I\u2019ve just remembered bin day and I don\u2019t trust myself.",
  "I\u2019m in witness protection from small talk.",
  "Not tonight \u2014 a mate had a relative whose dog ate something it shouldn't and the vet bill story lives rent-free.",
  "I\u2019ve disappointed the sofa by standing up once already.",
  "Not tonight \u2014 my gran got involved in something like this and had to write a letter of apology to Tesco.",
  "Not tonight \u2014 something about the way a neighbour looks at their fence makes me think there's a story.",
  "I've lost one of my favourite fuzzy socks. I can't possibly feel sexy when I have one cold foot and one warm foot. It's a sensory nightmare.\"",
  "I can't \u2014 my grandad mentioned doing this and his face suggested he's never recovered.",
  "I can\u2019t \u2014 I sneezed and something shifted permanently.",
  "Can\u2019t do it. My nightie\u2019s got a very low neckline tonight and it\u2019s making promises I can\u2019t keep.",
  "Not tonight \u2014 my MIL's got that look on her face and I know what it means.",
  "I can't \u2014 I'm in the middle of deciding whether to text someone I shouldn't and I need to stay focused on that.",
  "I can't \u2014 my bed sheets are at that stage and I'm considering my options.",
  "Not tonight \u2014 a friend's said something to someone else and now there's a whole thing and I'm implicated.",
  "I can't \u2014 I've decided I deserve a night where reality doesn't shrink on contact.",
  "I can't \u2014 I know about another friend's embarrassing incident at a supermarket checkout and I can never unsee that place the same way.",
  "I can't \u2014 I'm watching someone on a baking show make a critical error and I need to stay to see if the judges notice.",
  "Darling, no \u2014 I\u2019ve got to finish writing a stern letter to the council about bin day.",
  "I can't \u2014 I saw someone looking at their house from outside in a way that made me question what they were planning.",
  "Can\u2019t \u2014 I\u2019ve got to rewatch a show I don\u2019t even like out of sheer stubbornness.",
  "The chocolate is already melting in my hand. It\u2019s too late.",
  "Not tonight \u2014 I\u2019m halfway through judging the neighbours silently through the blinds.",
  "Not tonight \u2014 I watched a neighbour's cat get stuck somewhere and now I have opinions about it.",
  "I can't \u2014 there's a smell in the bathroom and the source investigation is ongoing.",
  "Sorry \u2014 I\u2019ve started a documentary about castles and I\u2019m in too deep now.",
  "I can't \u2014 I need to recover from the last time someone promised something they couldn't deliver.",
  "Not tonight, pet \u2014 I\u2019ve promised the vicar I\u2019d keep my hands on something wholesome. The remote, mainly.",
  "Not tonight \u2014 my bowels are in a mood and I need to be home for support.",
  "Not tonight \u2014 Edna said, 'The council won't like it,' and she's never been wrong about the council.",
  "I would, but Norma's cat has gone missing again and I've got to stand in the garden with a torch making clicking noises.\"",
  "I'd love to, but my hot-water bottle has developed feelings and tonight's the night we have The Talk.",
  "Not tonight \u2014 I'm not in the mood to pretend.",
  "I would, but I've just remembered I don't want to.\"",
  "Not tonight\u2014I\u2019ve got a very demanding cat who insists on being the only thing I stroke after 9pm.",
  "I can't \u2014 my face is doing something that requires concealer I haven't got time for.",
  "Not tonight \u2014 my knickers have staged a rebellion and I'm not in a position to negotiate with them.",
  "I can't \u2014 my mother-in-law's going to judge something and I'm not in the headspace for it.",
  "Not tonight \u2014 something's leaked and I've got a stain situation that won't come out quickly.",
  "I can't. I've just remembered something I said in 1987 and I need to sit with that for a while.",
  "Not tonight \u2014 the charity shop on the corner and I have a situation.",
  "I can't \u2014 I've made peace with one underwhelming situation and I'm not inviting another.",
  "I can't \u2014 there's a night sweat situation and I've changed my clothes twice already.",
  "Not tonight \u2014 I\u2019m in the middle of a very heated argument with the television.",
  "I can't \u2014 something's riding up and the solution requires removal and I'm staying home.",
  "The guinea pig just stared at me like I owe him money.",
  "Not tonight \u2014 something's happening with my hormones that's making me emotional and unpredictable."
]
};

export const TOTAL_QUOTES = QUOTES_364.free.length + QUOTES_364.unlocked.length;

